apiVersion: v1
kind: ConfigMap
metadata:
  name: "paul-cm"
data:
  temporal: |
    {{ toJson .Values.temporal }}
  
  dialogflow: |
    {{ toJson .Values.dialogflow }}

  workflows: |
    {{ toJson .Values.workflow }}